# Generated by Django 4.1.2 on 2022-10-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=280, unique=True)),
                ('last_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
